### ISSUE TITLE
Error in reading atomic density grid for heavy atoms 

### ISSUE THREAD

**Issue by yernaidu-reddi** [juliacontrerasgarcia/nciplot#10]
Hi,
I am doing NCI calculations for one of the metal complex systems. I have got the following error.
 
ERROR(nciplot): Some atomic density grids for heavy atoms are needed but not initialized
ERROR(nciplot): Some atomic density grids for heavy atoms are needed but not initialized
STOP 1

I have attached .xyz file. Could you please check it and provide possible solution for this issue asap.
https://drive.google.com/file/d/18OBjXPoZ1s8WJ9aohn_oyrpM0tE0DGis/view?usp=sharing

Thanks
Yernaidu

**Comment by rlaplaza** [comment]
Hello Yernaidu,

Sorry for the delay. Have you properly set up the home variable?

**Comment by brandon-meza** [comment]
Hello!

I'm facing the same problem when using Pd in Promolecular approximation:

> File: /home/user/nciplot/src_nciplot_4.0/dat/pd_lda.wfc
> WARNING(readgrid): Atomic density file not found
> ERROR(nciplot): Some atomic density grids for heavy atoms are needed but not initialized
> ERROR(nciplot): Some atomic density grids for heavy atoms are needed but not initialized
> STOP 1

I found the pd_lda.wfc file in /home/user/nciplot/dat and also I am able to run the program when I remove this atom from the xyz file. 

Is there something that I can do?

Regards

**Comment by rlaplaza** [comment]
Hello! Have you set up the home variable as pointed out in the README?
Running

`echo $NCIPLOT_HOME`

should point to the nciplot directory in that path, which can be achieved by running

`export NCIPLOT_HOME=/home/user/nciplot/`

this is usually the problem.

**Comment by brandon-meza** [comment]
Hi! 
Thank you por response!

My $NCIPLOT_HOME points to this location:
`NCIPLOT_HOME=/home/user/nciplot/src_nciplot_4.0/`

Otherwise, I can not run the nciplot executable as `$NCIPlOT_HOME/nciplot`. With set up, that error message appears.

Nevertheless, I also tried with:
`NCIPLOT_HOME=/home/user/nciplot/`
And I can complete the calculation, but I have to run the nciplot exec from the src_nciplot_4.0/ folder. 

I think that I already understand the issue

Thank you for your time!

**Comment by rlaplaza** [comment]
Yes, you should keep the $NCIPLOT_HOME variable pointing to `/home/user/nciplot/` and to define how you want to run nciplot you can use an alias in your bashrc or add `/home/user/nciplot/src_nciplot_4.0/` to your path using `export`. 

Happy to help!
