### ISSUE TITLE
Crash when compiling with gcc

### ISSUE THREAD

**Issue by vliegeois** [juliacontrerasgarcia/nciplot#5]
Hi

I have two issues when compiling your code on my Mac using gfortran (gcc 10.1.0).
The code compile fine but then I have a crash when using the code in two different situations

1) Using the default grid, the program crashes when entering RANGE INTEGRATION DATA        
2) The second crash happens when using multiple grid

I was able to track down and to patch the two crashes

The first one is because with gcc, the logical variable dorange is initialise to .True. and not to .False. but srhorange is only allocated if the keyword RANGE is found.
 It is always better to initialise manually all variable and to no except any default behaviour from the compiler

The second one is because in the loop over the grids, when ind_g > 1, you reallocate some variables with the new size of the grid except celf.
What I don't completely understand in your reallocation is why using tmp variables such as tmp_crho and then using move_alloc (move_alloc( tmp_crho, crho )) and not directly check if crho is allocated and if yes deallocate it and then allocate the new size without tmp_crho. Is it for optimisation?

So in NCIplot.f90
line 151:
  logical :: dorange,flag_range(2,2,2)
-> 
  logical :: dorange=.False.,flag_range(2,2,2)

lines 658 -> 671
  if (ind_g .gt. 1) then
      if (allocated(tmp_crho)) deallocate(tmp_crho)
      allocate(tmp_crho(0:nstep(1)-1,0:nstep(2)-1,0:nstep(3)-1),stat=istat)
      call move_alloc( tmp_crho, crho )
      if (allocated(tmp_crho_n)) deallocate(tmp_crho_n)
      allocate(tmp_crho_n(0:nstep(1)-1,0:nstep(2)-1,0:nstep(3)-1, 1:nfiles),stat=istat)
      call move_alloc( tmp_crho_n, crho_n )
      if (allocated(tmp_cheigs)) deallocate(tmp_cheigs)
      allocate(tmp_cheigs(0:nstep(1)-1,0:nstep(2)-1,0:nstep(3)-1),stat=istat)
      call move_alloc( tmp_cheigs, cheig)
      if (allocated(tmp_cgrad)) deallocate(tmp_cgrad)
      allocate(tmp_cgrad(0:nstep(1)-1,0:nstep(2)-1,0:nstep(3)-1),stat=istat)
      call move_alloc( tmp_cgrad, cgrad )
  end if
->
  if (ind_g .gt. 1) then
      if (allocated(tmp_crho)) deallocate(tmp_crho)
      allocate(tmp_crho(0:nstep(1)-1,0:nstep(2)-1,0:nstep(3)-1),stat=istat)
      call move_alloc( tmp_crho, crho )
      if (allocated(tmp_crho_n)) deallocate(tmp_crho_n)
      allocate(tmp_crho_n(0:nstep(1)-1,0:nstep(2)-1,0:nstep(3)-1, 1:nfiles),stat=istat)
      call move_alloc( tmp_crho_n, crho_n )
      if (allocated(tmp_cheigs)) deallocate(tmp_cheigs)
      allocate(tmp_cheigs(0:nstep(1)-1,0:nstep(2)-1,0:nstep(3)-1),stat=istat)
      call move_alloc( tmp_cheigs, cheig)
      if (allocated(tmp_cgrad)) deallocate(tmp_cgrad)
      allocate(tmp_cgrad(0:nstep(1)-1,0:nstep(2)-1,0:nstep(3)-1),stat=istat)
      call move_alloc( tmp_cgrad, cgrad )
      if (doelf) then
        if (allocated(celf)) deallocate(celf)
        allocate(celf(0:nstep(1)-1,0:nstep(2)-1,0:nstep(3)-1),stat=istat)
      endif
  end if

Maybe you should also check that all variables received manually a initial value before being used

Best regards

Vincent

PS

I'm developing a graphical code on MacOS call DrawMol to visualise the NCI.
I'm able to read the grad.cube file and to use the dens.cube file as a texture to produce images similar to what vmd can do.
But I would like to be able to do that directly into my program so I would like to discuss with you about the possibility to incorpore NCI directly into DrawMol.
If you are interested, you can contact me at vincent.liegeois@unamur.be

**Comment by vliegeois** [comment]
Hi

I have realised why the missing reallocation of celf when having multiple grids was not an issue with intel, it's because again doelf logical variable at line 86 of nciplot.f90 was never initialise so intel initialise it to false but gcc initialise logical variable to true by default.

Please initialise all variables, especially logical ones yourself and don't expect the compiler to do it for you

Regards

Vincent

**Comment by rlaplaza** [comment]
The newest release should have fixed this issue (among others). 

Sometimes its hard to test over all compilers. Thank you for your input!

**Comment by rlaplaza** [comment]
I will add that, in fact, the ELF part was meant to be removed in the release of NCIplot 4.0. There are many codes that do ELF just fine. I take this is a closed issue now!
