### ISSUE TITLE
Can't run calculation with xyz file

### ISSUE THREAD

**Issue by vliegeois** [juliacontrerasgarcia/nciplot#7]
Hi

When running a nciplot calculation on xyz file, I have the following error that appears at several places:

ERROR(calcprops): unknown ixc option

To fix this issue, I have modify line 89 in nciplot.f90:
  integer :: ixc(2)
->
  integer :: ixc(2) = 0

Indeed, ixc variable is not initialized before being passed as an input parameter to the function 
call calcprops_pro

I assume that the initial value should be zero.
Is this correct?

Best regards

Vincent

**Comment by rlaplaza** [comment]
I think this one should be fixed as well. The part of the code dealing with exchange-correlation energies and ELF has been removed for the most part.
